env:
  browser: false
  commonjs: true
  es6: true
extends:
  - "eslint:recommended"
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  strict: off
  no-console: off
  no-unused-vars: warn
